### ISSUE TITLE
Use for Astropy

### ISSUE THREAD

**Issue by saimn** [MeeseeksBox/MeeseeksDev#48]
Hi @Carreau,

We would like to use @MeeseeksDev to backport PRs for Astropy. We are currently testing it, we installed the app and @MeeseeksDev seems to be already responding to our comments, and it looks great ! Thanks for the tool.
I'm reaching you as it seems you have a whitelist of users/orgs, and I'm not sure if something needs to be done here ?

Also is there a way to add specific labels on backported PRs ? I found a mention of something similar, `on-merge: say "Oh Weeeee"`, so I'm guessing we could use `on-merge: tag some-label` ? (Not sure if this would apply to the backport PR though ?)

**Comment by pllim** [comment]
Actually, applying a specific label on open would also be nice. If it can apply `skip-basebranch-check`, then we don't have to disable to basebranch check. See https://github.com/astropy/astropy/pull/11793#issuecomment-848887727

But if that is no-go, we can also opt to apply that label on the PR to be backported before backport happens because according to the README here, "Apply origin-pr labels and milestone to backport." Though in practice, I see the milestone being applied but not the labels.

**Comment by saimn** [comment]
> Though in practice, I see the milestone being applied but not the labels.

Should be fixed with #49 :)

**Comment by Carreau** [comment]
I see from https://meeseeksbox.github.io/ that it seem to be backporting fine, and that @QuLogic helped you, let me know if there is anything else I can do to help !

**Comment by saimn** [comment]
@Carreau - yes it seems to be working fine, thanks for the tool ! And we found a solution to avoid the need to add a label to the backport PR so all good for now.
