### ISSUE TITLE
Backport via label did not trigger

### ISSUE THREAD

**Issue by pllim** [MeeseeksBox/MeeseeksDev#50]
https://meeseeksbox.github.io/ mentioned that it is possible to trigger backport via label as long as description has the directive. Over at https://github.com/astropy/astropy/labels , we have a `backport-v4.3.x` label with the description as required. But when applied to, say astropy/astropy#11971, it did not trigger backport bot to open a backport PR on merge. What did we do wrong? Hope you can advise. Thanks!

**Comment by Carreau** [comment]
Hum, I think the issue is arround here:

https://github.com/MeeseeksBox/MeeseeksDev/blob/6b733c284c9107968775919728ebae4fdca0fa06/meeseeksdev/meeseeksbox/core.py#L376-L383

1) it looks only at the milestone
2) it should check for the repo base branch and not hardcoded `"master"`.

I can't promise I'll fix this soon, but I can give you access to this repo and heroku if you want to try to fix it yourself.

**Comment by Carreau** [comment]
Oh, actually the labels are taken care of a bit higher, so it might just be "master"/"main" I've tried to push a workaround.

**Comment by pllim** [comment]
Thanks! I'll keep an eye on it and report back. We don't backport every day.

**Comment by Carreau** [comment]
Seeing https://github.com/MeeseeksBox/test1/pull/84 that should work now.

**Comment by pllim** [comment]
Yay, it indeed works now. Thank you so much for the quick fix!
